title: Benoît de Courson
url: "https://regicid.github.io"

markdown: kramdown
kramdown:
   math_engine: mathjax
tracking_id: UA-85678197-1

sass:
    style: compressed
    sass_dir: _sass
nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "CV_english.pdf"
 - name: "Contact"
   link: "contact"
   
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending
  
  bibliography: references
  bibliography_template: <abbr>[{{key}}]</abbr>{{reference}}

  replace_strings: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
